services:
    all-hands-ai:
        image: 'docker.all-hands.dev/all-hands-ai/openhands:0.54'
        container_name: openhands-app-54
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '3000:3000'
        volumes:
            - '~/.openhands:/.openhands'
            - '/var/run/docker.sock:/var/run/docker.sock'
        environment:
            - LLM_RETRY_MULTIPLIER=1.5
            - LLM_RETRY_MAX_WAIT=60
            - LLM_RETRY_MIN_WAIT=8
            - LLM_NUM_RETRIES=5
            - LOG_ALL_EVENTS=true
            - LOG_ALL_EVENTS=true
            - 'SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.54-nikolaik'
        pull_policy: always
        tty: true
        stdin_open: true
