spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/delivery}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# Show SQL in logs
spring.jpa.show-sql=true

# Context path para que coincida con los servers definidos en openapi.yml
server.servlet.context-path=/api

# Springdoc: configuramos Swagger UI para cargar el OpenAPI estatico expuesto en /v3/api-docs.yaml
springdoc.swagger-ui.url=/v3/api-docs.yaml
springdoc.swagger-ui.enabled=true

# Liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=${LIQUIBASE_ENABLED:true}

